# -*- coding: utf-8 -*-
"""File 01: : A-Computational-Social-Science-Study-of-Development-Environmental-Trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCeQy9eEYq-b6uHs-OyKfrBWw-EfozPr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_csv('Dataset 1.csv')

import pandas as pd
df1.columns = df1.columns.str.replace('.00', '', regex=False)
df = df1.drop(columns=['Unnamed: 34'], errors='ignore')
print(df.columns)

developed_countries = [
    "United States", "United Kingdom", "Germany", "France", "Japan",
    "Canada", "Italy", "Australia", "South Korea", "Spain",
    "Netherlands", "Sweden", "Switzerland", "Norway", "Denmark",
    "Finland", "Belgium", "Austria", "Ireland", "New Zealand",
    "Singapore", "Israel", "Portugal", "Greece", "Czech Republic",
    "Slovenia", "Slovak Republic", "Estonia", "Latvia", "Lithuania",
    "Luxembourg", "Iceland", "Malta", "Cyprus"
]

developing_countries = [
    'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia', 'Azerbaijan',
    'Bangladesh', 'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Cabo Verde', 'Cambodia',
    'Cameroon', 'China', 'Colombia', 'Comoros', 'Congo, Rep.', "Cote d'Ivoire",
    'Cuba', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
    'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eswatini', 'Fiji',
    'Gabon', 'Georgia', 'Ghana', 'Grenada', 'Guatemala', 'Guinea', 'Haiti',
    'Honduras', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Jamaica',
    'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kyrgyz Republic', 'Lao PDR',
    'Lebanon', 'Lesotho', 'Libya', 'Malaysia', 'Maldives', 'Marshall Islands',
    'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Moldova',
    'Mongolia', 'Morocco', 'Myanmar', 'Namibia', 'Nepal', 'Nicaragua', 'Nigeria',
    'North Macedonia', 'Pakistan', 'Papua New Guinea', 'Paraguay', 'Peru',
    'Philippines', 'Samoa', 'Sao Tome and Principe', 'Senegal', 'Solomon Islands',
    'South Africa', 'Sri Lanka', 'St. Lucia', 'St. Vincent and the Grenadines',
    'Suriname', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Tonga',
    'Tunisia', 'Turkiye', 'Turkmenistan', 'Tuvalu', 'Ukraine', 'Uzbekistan',
    'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Zambia', 'Zimbabwe'
]

underdeveloped_countries = [
    'Afghanistan', 'Burkina Faso', 'Burundi', 'Central African Republic', 'Chad',
    'Congo, Dem. Rep.', 'Eritrea', 'Ethiopia', 'Gambia, The', 'Guinea-Bissau',
    "Korea, Dem. People's Rep.", 'Liberia', 'Madagascar', 'Malawi', 'Mali',
    'Mozambique', 'Niger', 'Rwanda', 'Sierra Leone', 'Somalia',
    'Syrian Arab Republic', 'Togo', 'Uganda', 'Yemen, Rep.'
]

import pandas as pd
import altair as alt
years = [str(year) for year in range(1991, 2023)]
df_long = df.melt(
    id_vars=['Country Name'],
    value_vars=years,
    var_name='Year',
    value_name='Agri_Land_Percent')
df_long['Year'] = pd.to_datetime(df_long['Year'], format='%Y')
df_long = df_long.dropna(subset=['Agri_Land_Percent'])

import plotly.express as px
df_long['Year_Int'] = df_long['Year'].dt.year
df_long = df_long.sort_values('Year_Int')

"""# Group 1: Developed Countries"""

df_dev = df_long[df_long['Country Name'].isin(developed_countries)]
fig_dev = px.choropleth(
    df_dev,
    locations="Country Name",
    locationmode="country names",
    color="Agri_Land_Percent",
    hover_name="Country Name",
    animation_frame="Year_Int",
    color_continuous_scale=px.colors.sequential.YlGn,
    range_color=[0, 100],
    title="Agricultural Land (% of land area) - Developed Countries (1991-2022)",
    template="ggplot2")
fig_dev.update_geos(projection_type="natural earth", showcoastlines=True, coastlinecolor="Black")
fig_dev.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
fig_dev.show()

df_dev = df_long[df_long['Country Name'].isin(developing_countries)]
fig_dev = px.choropleth(
    df_dev,
    locations="Country Name",
    locationmode="country names",
    color="Agri_Land_Percent",
    hover_name="Country Name",
    animation_frame="Year_Int",
    color_continuous_scale=px.colors.sequential.YlGn,
    range_color=[0, 100],
    title="Agricultural Land (% of land area) - Developing Countries (1991-2022)",
    template="ggplot2")
fig_dev.update_geos(projection_type="natural earth", showcoastlines=True, coastlinecolor="Black")
fig_dev.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
fig_dev.show()

df_dev = df_long[df_long['Country Name'].isin(underdeveloped_countries)]
fig_dev = px.choropleth(
    df_dev,
    locations="Country Name",
    locationmode="country names",
    color="Agri_Land_Percent",
    hover_name="Country Name",
    animation_frame="Year_Int",
    color_continuous_scale=px.colors.sequential.YlGn,
    range_color=[0, 100],
    title="Agricultural Land (% of land area) - Underdeveloped Countries (1991-2022)",
    template="ggplot2")
fig_dev.update_geos(projection_type="natural earth", showcoastlines=True, coastlinecolor="Black")
fig_dev.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
fig_dev.show()

df2 = pd.read_csv('Dataset 2.csv')

import pandas as pd
df2.columns = df2.columns.str.replace('.00', '', regex=False)
df = df1.drop(columns=['Unnamed: 34'], errors='ignore')
print(df.columns)

year_columns = [col for col in df2.columns if col not in ['Country Name', 'Series Name']]
df_forest_long = pd.melt(
    df2,
    id_vars=['Country Name', 'Series Name'],
    value_vars=year_columns,
    var_name='Year',
    value_name='Forest Area (%)')
df_forest_long['Year_Int'] = df_forest_long['Year'].astype(float).astype(int)
df_forest_long['Forest Area (%)'] = pd.to_numeric(df_forest_long['Forest Area (%)'], errors='coerce')
df_forest_long = df_forest_long.dropna(subset=['Forest Area (%)'])
df_forest_long = df_forest_long.sort_values('Year_Int')

"""# Developed Countries"""

df_developed = df_forest_long[df_forest_long['Country Name'].isin(developed_countries)]
fig_developed = px.scatter_geo(
    df_developed,
    locations="Country Name",
    locationmode="country names",
    color="Forest Area (%)",
    size="Forest Area (%)",
    hover_name="Country Name",
    animation_frame="Year_Int",
    color_continuous_scale="Greens",
    range_color=[0, 100],
    size_max=40,
    title="Forest Area (%): Developed Countries (Bubble Map)")
fig_developed.update_geos(projection_type="natural earth", fitbounds="locations")
fig_developed.show()

"""# Developing Countries"""

df_developing = df_forest_long[df_forest_long['Country Name'].isin(developing_countries)]
fig_developing = px.scatter_geo(
    df_developing,
    locations="Country Name",
    locationmode="country names",
    color="Forest Area (%)",
    size="Forest Area (%)",
    hover_name="Country Name",
    animation_frame="Year_Int",
    color_continuous_scale="Greens",
    range_color=[0, 100],
    size_max=40,
    title="Forest Area (%): Developing Countries (Bubble Map)")
fig_developing.update_geos(projection_type="natural earth", fitbounds="locations")
fig_developing.show()

"""# Underdeveloped Countries"""

df_underdeveloped = df_forest_long[df_forest_long['Country Name'].isin(underdeveloped_countries)]
fig_underdeveloped = px.scatter_geo(
    df_underdeveloped,
    locations="Country Name",
    locationmode="country names",
    color="Forest Area (%)",
    size="Forest Area (%)",
    hover_name="Country Name",
    animation_frame="Year_Int",
    color_continuous_scale="Greens",
    range_color=[0, 100],
    size_max=40,
    title="Forest Area (%): Underdeveloped Countries (Bubble Map)")
fig_underdeveloped.update_geos(projection_type="natural earth", fitbounds="locations")
fig_underdeveloped.show()

"""# Cartogram

# Area Visual: Developed Countries (Treemap)
"""

df_developed = df_forest_long[df_forest_long['Country Name'].isin(developed_countries)]
df_dev_2022 = df_developed[df_developed['Year_Int'] == 2022]
df_dev_2022 = df_dev_2022[df_dev_2022['Forest Area (%)'] > 0]
fig_developed = px.treemap(
    df_dev_2022,
    path=[px.Constant("Developed Countries"), 'Country Name'],
    values='Forest Area (%)',
    color='Forest Area (%)',
    color_continuous_scale="Greens",
    title="Forest Area Proportional Size: Developed Countries (2022)")
fig_developed.update_traces(root_color="lightgrey")
fig_developed.show()

"""# Area Visual: Developing Countries (Treemap)"""

df_developing = df_forest_long[df_forest_long['Country Name'].isin(developing_countries)]
df_dev_ing_2022 = df_developing[df_developing['Year_Int'] == 2022]
df_dev_ing_2022 = df_dev_ing_2022[df_dev_ing_2022['Forest Area (%)'] > 0]
fig_developing = px.treemap(
    df_dev_ing_2022,
    path=[px.Constant("Developing Countries"), 'Country Name'],
    values='Forest Area (%)',
    color='Forest Area (%)',
    color_continuous_scale="Greens",
    title="Forest Area Proportional Size: Developing Countries (2022)")
fig_developing.update_traces(root_color="lightgrey")
fig_developing.show()

"""# Area Visual: Underdeveloped Countries (Treemap)"""

df_underdeveloped = df_forest_long[df_forest_long['Country Name'].isin(underdeveloped_countries)]
df_underdev_2022 = df_underdeveloped[df_underdeveloped['Year_Int'] == 2022]
df_underdev_2022 = df_underdev_2022[df_underdev_2022['Forest Area (%)'] > 0]
fig_underdeveloped = px.treemap(
    df_underdev_2022,
    path=[px.Constant("Underdeveloped Countries"), 'Country Name'],
    values='Forest Area (%)',
    color='Forest Area (%)',
    color_continuous_scale="Greens",
    title="Forest Area Proportional Size: Underdeveloped Countries (2022)")
fig_underdeveloped.update_traces(root_color="lightgrey")
fig_underdeveloped.show()

df3 = pd.read_csv('Dataset 3.csv')

"""# Prepare the Data"""

df_dev = df_long[df_long['Country Name'].isin(developed_countries)]
df_dev_avg = df_dev.groupby('Year')['Value'].mean().reset_index()
fig1 = px.area(df_dev_avg, x='Year', y='Value',
               title='<b>Developed Countries</b><br><sup>Renewable energy consumption (% of total)</sup>',
               labels={'Value': 'Renewable Energy (%)'},
               color_discrete_sequence=['#2D5A27'])
fig1.update_traces(line_width=3, fillcolor='rgba(45, 90, 39, 0.2)')
fig1.update_layout(
    template='plotly_white',
    hovermode='x unified',
    xaxis=dict(showgrid=False, rangeslider=dict(visible=True)),
    yaxis=dict(ticksuffix="%", gridcolor='#ebebeb'))
fig1.show()

df_ing = df_long[df_long['Country Name'].isin(developing_countries)]
df_ing_avg = df_ing.groupby('Year')['Value'].mean().reset_index()
fig2 = px.area(df_ing_avg, x='Year', y='Value',
               title='<b>Developing Countries</b><br><sup>Renewable energy consumption (% of total)</sup>',
               labels={'Value': 'Renewable Energy (%)'},
               color_discrete_sequence=['#008080'])
fig2.update_traces(line_width=3, fillcolor='rgba(0, 128, 128, 0.2)')
fig2.update_layout(
    template='plotly_white',
    hovermode='x unified',
    xaxis=dict(showgrid=False, rangeslider=dict(visible=True)),
    yaxis=dict(ticksuffix="%", gridcolor='#ebebeb'))
fig2.show()

df_under = df_long[df_long['Country Name'].isin(underdeveloped_countries)]
df_under_avg = df_under.groupby('Year')['Value'].mean().reset_index()
fig3 = px.area(df_under_avg, x='Year', y='Value',
               title='<b>Underdeveloped Countries</b><br><sup>Renewable energy consumption (% of total)</sup>',
               labels={'Value': 'Renewable Energy (%)'},
               color_discrete_sequence=['#708238'])
fig3.update_traces(line_width=3, fillcolor='rgba(112, 130, 56, 0.2)')
fig3.update_layout(
    template='plotly_white',
    hovermode='x unified',
    xaxis=dict(showgrid=False, rangeslider=dict(visible=True)),
    yaxis=dict(ticksuffix="%", gridcolor='#ebebeb'))
fig3.show()

df4 = pd.read_csv('Dataset 4.csv')

"""# Data Cleaning"""

import plotly.express as px
df4 = pd.read_csv('Dataset 4.csv')
year_columns = [col for col in df4.columns if col not in ['Country Name', 'Series Name']]
df_water = pd.melt(df4, id_vars=['Country Name'], value_vars=year_columns, var_name='Year', value_name='Water Stress')
df_water['Water Stress'] = pd.to_numeric(df_water['Water Stress'], errors='coerce')
df_water['Year'] = df_water['Year'].astype(int)
df_water = df_water.dropna()

"""# Developed Countries: Water Stress Levels"""

df_dev_water = df_water[df_water['Country Name'].isin(developed_countries)]
df_dev_avg = df_dev_water.groupby('Year')['Water Stress'].mean().reset_index()
fig1 = px.area(df_dev_avg, x='Year', y='Water Stress',
               title='<b>Developed Countries</b><br><sup>Level of Water Stress (Withdrawal as % of Resources)</sup>',
               color_discrete_sequence=['#3498db'])
fig1.add_hline(y=25, line_dash="dash", line_color="orange", annotation_text="Stress Threshold (25%)")

fig1.update_layout(template='plotly_white', yaxis=dict(ticksuffix="%"))
fig1.show()

"""# Developing Countries: Water Stress Levels"""

df_ing_water = df_water[df_water['Country Name'].isin(developing_countries)]
df_ing_avg = df_ing_water.groupby('Year')['Water Stress'].mean().reset_index()
fig2 = px.area(df_ing_avg, x='Year', y='Water Stress',
               title='<b>Developing Countries</b><br><sup>Level of Water Stress (Withdrawal as % of Resources)</sup>',
               color_discrete_sequence=['#2980b9'])
fig2.add_hline(y=25, line_dash="dash", line_color="orange", annotation_text="Stress Threshold (25%)")

fig2.update_layout(template='plotly_white', yaxis=dict(ticksuffix="%"))
fig2.show()

"""# Underdeveloped Countries: Water Stress Levels"""

df_under_water = df_water[df_water['Country Name'].isin(underdeveloped_countries)]
df_under_avg = df_under_water.groupby('Year')['Water Stress'].mean().reset_index()
fig3 = px.area(df_under_avg, x='Year', y='Water Stress',
               title='<b>Underdeveloped Countries</b><br><sup>Level of Water Stress (Withdrawal as % of Resources)</sup>',
               color_discrete_sequence=['#1a5276'])
fig3.add_hline(y=25, line_dash="dash", line_color="orange", annotation_text="Stress Threshold (25%)")
fig3.update_layout(template='plotly_white', yaxis=dict(ticksuffix="%"))
fig3.show()

df5 = pd.read_csv('Dataset 5.csv')

"""# Data Cleaning"""

import plotly.express as px
df5 = pd.read_csv('Dataset 5.csv')
year_columns = [col for col in df5.columns if col not in ['Country Name', 'Series Name']]
df_co2 = pd.melt(df5, id_vars=['Country Name'], value_vars=year_columns, var_name='Year', value_name='CO2')
df_co2['CO2'] = pd.to_numeric(df_co2['CO2'], errors='coerce')
df_co2['Year'] = df_co2['Year'].astype(int)
df_co2 = df_co2.dropna()

"""# Developed Countries: The "Carbon Giants" Visual"""

df_dev = df_co2[df_co2['Country Name'].isin(developed_countries)]
df_dev_avg = df_dev.groupby('Year')['CO2'].mean().reset_index()
fig1 = px.scatter(df_dev_avg, x="Year", y="CO2",
                 size="CO2", color="CO2",
                 text=df_dev_avg['CO2'].round(1),
                 title="<b>Developed Countries: CO2 Footprint</b><br><sup>Metric tons per capita (Average)</sup>",
                 color_continuous_scale="Reds")
fig1.update_traces(mode='lines+markers+text', textposition='top center', marker_sizeref=0.5)
fig1.update_layout(template='plotly_white', coloraxis_showscale=False, yaxis_range=[0, max(df_dev_avg['CO2'])+5])
fig1.show()

"""# Developing Countries: The "Transition" Visual"""

df_ing = df_co2[df_co2['Country Name'].isin(developing_countries)]
df_ing_avg = df_ing.groupby('Year')['CO2'].mean().reset_index()
fig2 = px.scatter(df_ing_avg, x="Year", y="CO2",
                 size="CO2", color="CO2",
                 text=df_ing_avg['CO2'].round(1),
                 title="<b>Developing Countries: CO2 Footprint</b><br><sup>The industrialization trend</sup>",
                 color_continuous_scale="Oranges")
fig2.update_traces(mode='lines+markers+text', textposition='top center', marker_sizeref=1.5)
fig2.update_layout(template='plotly_white', coloraxis_showscale=False, yaxis_range=[0, max(df_ing_avg['CO2'])+2])
fig2.show()

"""# Underdeveloped Countries: The "Low Impact" Visual"""

df_under = df_co2[df_co2['Country Name'].isin(underdeveloped_countries)]
df_under_avg = df_under.groupby('Year')['CO2'].mean().reset_index()
fig3 = px.scatter(df_under_avg, x="Year", y="CO2",
                 size="CO2", color="CO2",
                 text=df_under_avg['CO2'].round(2),
                 title="<b>Underdeveloped Countries: CO2 Footprint</b><br><sup>Minimum carbon intensity</sup>",
                 color_continuous_scale="YlOrBr")
fig3.update_traces(mode='lines+markers+text', textposition='top center', marker_sizeref=5)
fig3.update_layout(template='plotly_white', coloraxis_showscale=False, yaxis_range=[0, max(df_under_avg['CO2'])+1])
fig3.show()

df6 = pd.read_csv('Dataset 6.csv')

"""# Data Setup"""

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
df6 = pd.read_csv('Dataset 6.csv')
year_columns = [col for col in df6.columns if col not in ['Country Name', 'Series Name']]
df_spei = pd.melt(df6, id_vars=['Country Name'], value_vars=year_columns, var_name='Year', value_name='SPEI')
df_spei['SPEI'] = pd.to_numeric(df_spei['SPEI'], errors='coerce')
df_spei['Year'] = df_spei['Year'].astype(int)
df_spei = df_spei.dropna(subset=['SPEI'])

"""# Developed Countries: Drought & Wet Cycles"""

df_dev_avg = df_spei[df_spei['Country Name'].isin(developed_countries)].groupby('Year')['SPEI'].mean().reset_index()
fig1 = go.Figure()
fig1.add_trace(go.Bar(
    x=df_dev_avg['Year'],
    y=df_dev_avg['SPEI'],
    marker_color=df_dev_avg['SPEI'],
    marker_colorscale='RdBu',
    marker_cmid=0,
    name='SPEI Index'))
fig1.update_layout(
    title='<b>Developed Countries: Drought & Wet Cycles</b><br><sup>SPEI Index (Positive = Wet, Negative = Dry)</sup>',
    template='plotly_white',
    xaxis_title="Year",
    yaxis_title="SPEI Index",
    yaxis=dict(zeroline=True, zerolinewidth=2, zerolinecolor='black'))
fig1.show()

"""# Developing Countries: Drought & Wet Cycles"""

df_ing_avg = df_spei[df_spei['Country Name'].isin(developing_countries)].groupby('Year')['SPEI'].mean().reset_index()
fig2 = go.Figure()
fig2.add_trace(go.Bar(
    x=df_ing_avg['Year'],
    y=df_ing_avg['SPEI'],
    marker_color=df_ing_avg['SPEI'],
    marker_colorscale='RdBu',
    marker_cmid=0,
    name='SPEI Index'))
fig2.update_layout(
    title='<b>Developing Countries: Drought & Wet Cycles</b><br><sup>SPEI Index (Departure from long-term normal)</sup>',
    template='plotly_white',
    xaxis_title="Year",
    yaxis_title="SPEI Index",
    yaxis=dict(zeroline=True, zerolinewidth=2, zerolinecolor='black'))
fig2.show()

"""# Underdeveloped Countries: Drought & Wet Cycles"""

df_under_avg = df_spei[df_spei['Country Name'].isin(underdeveloped_countries)].groupby('Year')['SPEI'].mean().reset_index()
fig3 = go.Figure()
fig3.add_trace(go.Bar(
    x=df_under_avg['Year'],
    y=df_under_avg['SPEI'],
    marker_color=df_under_avg['SPEI'],
    marker_colorscale='RdBu',
    marker_cmid=0,
    name='SPEI Index'))
fig3.update_layout(
    title='<b>Underdeveloped Countries: Drought & Wet Cycles</b><br><sup>SPEI Index (Drought intensity over time)</sup>',
    template='plotly_white',
    xaxis_title="Year",
    yaxis_title="SPEI Index",
    yaxis=dict(zeroline=True, zerolinewidth=2, zerolinecolor='black'))
fig3.show()

